### ISSUE TITLE
"apply an orientation lock" should reference firing event 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/screen-orientation#51]
Elsewhere, @dontcallmedom wrote: 

> shouldn't the "apply an orientation lock" algorithm make reference to 
> the event firing? I was having trouble understanding steps 8.2 and 8.3 
> in the former until I arrived to the latter

**Comment by mounirlamouri** [comment]
I remember that the description used to do that but it was pretty confusing, mostly because applying an orientation lock doesn't have to change the current screen orientation so it might or might not fire an event. Making that part clear and short would be an tedious exercise.

The spec is fairly small and (I hope) well structured. It's probably not too much asked to the user to read the entire section 5 (Concepts) in order to understand it all. Marking as WONTFIX.
