### ISSUE TITLE
Rename variables to more clearly indicate what is a list

### ISSUE THREAD

**Issue by annevk** [w3c/screen-orientation#66]
Given https://github.com/mounirlamouri/screen-orientation/commit/f69832082f7ef78bdb6d2274d99d2ad3c9d5de16 it's still not clear to me how these are not lists or sets. `orientations` is plural so what is going?

**Comment by mounirlamouri** [comment]
The current prose is:
`A document's orientation lock is the orientation lock that applies on its top-level browsing context. An orientation lock is a set of OrientationType.`

I believe it is clearly described as a set, right?

Please reopen if you disagree.

**Comment by annevk** [comment]
I have no reopen powers in this repository.

However, if it's a set, why not call it that? Why name it orientation lock rather than orientation lock set?

The whole problem here is that you do things like "If the active orientation lock is not the document's orientation lock, abort these steps." without explaining how you compare sets in this way. Are (x, y) and (y, x) different or identical sets? You really ought to explain this better.

**Comment by marcoscaceres** [comment]
(I'm just going to say, and I know you are going to hate me Anne, but it really helps us when you provide us with guidance like the above ... don't expect you to do our job for us, but still really helps!)

**Comment by annevk** [comment]
Well, in my very first email I thought it was a list and suggested you name it such and clarify the operations given that you operate on a list rather than a single value. Turns out it is a set, but the same comment applies.

**Comment by mounirlamouri** [comment]
> However, if it's a set, why not call it that? Why name it orientation lock rather than orientation lock set?

So, I did the change, read the spec with the change and I was not convinced. If I change "orientation lock" to "orientation lock set" I would have to change "active orientation lock" to "active orientation lock set" and so on. In my opinion, there is no need to suffix the concept with the type. It's mostly a taste or a convention. I think that addition makes the reading the specification more painful because you have to be reminded all the time that the thing is a set and I do not think it would help implementers.

> The whole problem here is that you do things like "If the active orientation lock is not the document's 
> orientation lock, abort these steps." without explaining how you compare sets in this way. Are (x, y)
> and (y, x) different or identical sets? You really ought to explain this better.

Algorithmically speaking, sets have no order so they are equal if they have the same elements. I do not think it is worth explaining that in the specification. (In other words, a set s1 is equal to another set s2 if all the elements of s1 are present in s2 and s1 and s2 have the same size.)

**Comment by mounirlamouri** [comment]
(Note: I've closed this issue mostly to reflect the fact that I do not think there is anything to do about this at the moment. It does not mean that you can't tell me that I'm wrong ;))

**Comment by annevk** [comment]
Not all sets are identical. E.g. sets in ECMAScript are ordered. Still seems bad.

**Comment by mounirlamouri** [comment]
To me, ordered or unordered for a set is an implementation detail in the sense that it will make iterating trough it faster and more reliable or not. I can also precise that the set in unordered to remove any confusion.

**Comment by marcoscaceres** [comment]
Given 7b9efdd, can we close this?

**Comment by marcoscaceres** [comment]
actually, never mind... it's already closed.
