### ISSUE TITLE
"unlocked" not explicitly defined

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/screen-orientation#81]
The manifest spec speaks of "unlocked" in the screen orientation spec, but the spec doesn't formally define what is means for an orientation to be unlocked. Would be nice to have an actual hook for that.

**Comment by marcoscaceres** [comment]
Section of the manifest spec:
https://w3c.github.io/manifest/#orientation-member

Relevant text: 

>  If the user agent honors the value of the orientation member as the default orientation, then that serves as the default orientation for the life of the web application (unless overridden by some other means at runtime). This means that the user agent MUST return the orientation to the default orientation any time the orientation is unlocked [SCREEN-ORIENTATION] or the top-level browsing context is navigated.

**Comment by mounirlamouri** [comment]
I'm not sure we should define unlocked. Setting the default orientation in that case should be enough. You only need "unlock" because you try to point to the places where the default orientation is used in the prose. It's kind of redundant.

Maybe you could just point at those as examples where the default orientation is used?

**Comment by marcoscaceres** [comment]
yeah, using default orientation might work.

**Comment by xfq** [comment]
It seems that we can close this issue now?
